### PR TITLE
Implement notEqual

### PR DESCRIPTION
**Pull request by BruceDai**
@fdwr @huningxin PTAL, thanks!

/cc @miaobin

### CODE REVIEW

**Review by fdwr — APPROVED** [review]
👍

**Review by huningxin — APPROVED** [review]

**Comment by huningxin** [comment]
@BruceDai , could you please take a look at bot failure?

**Comment by BruceDai** [comment]
> @BruceDai , could you please take a look at bot failure?

Yes, I've submitted a PR #115 for fixing this failure. Please help review and merge #115 firstly. ☕

**Comment by huningxin** [comment]
> Yes, I've submitted a PR #115 for fixing this failure. Please help review and merge #115 firstly. ☕

done, please have another try.

**Comment by fdwr** [comment]
@BruceDai - was closure an accident?

**Comment by BruceDai** [comment]
Sorry, I did it by misoperation. New submitted #118, PTAL, thanks!

**Pull request closed without merging**
