### PR TITLE
implement gatherElements

### PR DESCRIPTION
**Pull request by BruceDai**
@huningxin @fdwr @shiyi9801 PTAL, thanks.

### CODE REVIEW

**Review by fdwr — APPROVED** [review]
Thanks Bruce. Some small comments, and then LGTM.

**Comment by BruceDai** [comment]
@fdwr I've addressed your comments in the new commits, please take another look, thanks!

**Review by huningxin — APPROVED** [review]
LGTM!

**Review by fdwr — COMMENTED** [review]
👍 Thanks Bruce.

**Pull request merged**
